### ISSUE TITLE
Opening a drawer scrolls to the top again

### ISSUE THREAD

**Issue by mjxwb** [emilkowalski/vaul#152]
This is the same issue in #55, but the fix for it seems to have broken. Here is the bug again in the v0.7.5: 
 https://codesandbox.io/p/sandbox/drawer-scrolls-to-top-8lpqx9

**Comment by emilkowalski** [comment]
I can't reproduce this on Safari iOS 17. Can you provide reproduction instructions and which device you are using?

**Comment by DennieMello** [comment]
> I can't reproduce this on Safari iOS 17. Can you provide reproduction instructions and which device you are using?

I also encountered the problem of page scrolling up in my projects.

How to play:

I'm using next js 14 with an app router, the drawer is located in the layout and accordingly is initialized only once.

When I open the first page of the site and open the drawer, it does not scroll to the top, but if I then go to another page of the site and open the drawer, after closing it, the page scrolls to the top.

This is due to the fact that the drawer is initialized once and in the file use-position-fixed.ts the address of the page during initialization is written in the activeUrl, but when I go to another page, the activeUrl does not update and when I open the drawer, this code is executed, blocking scroll up.

```javascript
       if (activeUrl !== window.location.href) {
          setActiveUrl(window.location.href);
          return;
        }
``` 

For myself, I solved the problem by adding

```javascript
  const pathname = usePathname();

  React.useEffect(() => {
    if (!isOpen) {
      setActiveUrl(window.location.href);
    }
  }, [pathname, isOpen]);
``` 

I don’t know if this requires any changes, but just in case I described the problem I encountered =)

**Comment by dsbrianwebster** [comment]
Im actually experiencing this unwanted behavior on closing the drawer. The scroll position is undesirably jumping to the top of the page.

**Comment by dsbrianwebster** [comment]
Best I can do to prevent this and "keep" scroll position was double up the notion of scroll restoration...

```tsx
<Drawer
  open={modalType !== null}
  onClose={() => {
    drawerRestorePosition.current = document.body.style.getPropertyValue('top');
  }}
  onOpenChange={(open) => {
    if (!open) {
      requestAnimationFrame(() => {
        window.scrollTo(0, -parseInt(drawerRestorePosition.current, 10));
      });

      router.replace('/', { scroll: false });
    }
  }}
>
  <DrawerContent>
    {/* ... */}
  </DrawerContent>
</Drawer>
```

I don't love this. While it does effectively restore my scroll position it feels hack af and comes with an unavoidable content flicker on iOS devices. 

I'm beginning to think the whole approach to locking body scroll along with setPositionFixed and restorePositionSetting might need adjusting or even an alt solution. The underlying radix components effectively prevent body scrolling without the need for these techniques. 

I'm wonder if it is possible "keep" the pre-drawer scroll position without jump/flicker on touch device with the current approach of toggling from a position fixed + overflow hidden body + html back to the natural document flow.

**Comment by yousafsabir** [comment]
I am facing the same issue in next14. I used nextui's modal, which you can change the position. So by this I was able to replicate drawer

link: [NextUI's Modal](https://nextui.org/docs/components/modal)

**Comment by emilkowalski** [comment]
Can someone create a codesandbox demo that shows this problem and include your browser and device? It's hard to reproduce these issues consistently for me so I'd appreciate a demo, thank you!

**Comment by yoannakr** [comment]
Seems like the issue is caused by 
`
html {
  scroll-behavior: smooth;
}`

[Here is a codesandbox link](https://codesandbox.io/p/devbox/drawer-scrollable-forked-pvjf2x?embed=1&file=%2Fapp%2Fmy-drawer.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqxm9xz30007356j791696xt%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqxm9xz30002356jvtjow7bu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqxm9xz30004356jidy7x1ps%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqxm9xz30006356jjvnrkbw7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B57.66946575747542%252C42.33053424252458%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqxm9xz30002356jvtjow7bu%2522%253A%257B%2522id%2522%253A%2522clqxm9xz30002356jvtjow7bu%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxm9xz30001356jg0q31vh1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqya0ac600023n6p4o3hjxc9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A74%252C%2522startColumn%2522%253A16%252C%2522endLineNumber%2522%253A74%252C%2522endColumn%2522%253A16%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fmy-drawer.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqyywlrs0002356jacnxf5v8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqya0ac600023n6p4o3hjxc9%2522%257D%252C%2522clqxm9xz30006356jjvnrkbw7%2522%253A%257B%2522id%2522%253A%2522clqxm9xz30006356jjvnrkbw7%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxm9xz30005356jmzn8ulj2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqxm9xz30005356jmzn8ulj2%2522%257D%252C%2522clqxm9xz30004356jidy7x1ps%2522%253A%257B%2522id%2522%253A%2522clqxm9xz30004356jidy7x1ps%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqxm9xz30003356jqlpd9n3m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqxm9xz30003356jqlpd9n3m%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15.892712811247549%257D)

**Comment by emilkowalski** [comment]
@yoannakr Thank you, I will try to fix it somewhere this week once I have some time.

**Comment by daniel31x13** [comment]
@emilkowalski I'm facing the exact issue @yoannakr is facing, any updates?
And btw thanks for this awesome work, I'll definitely be using this for Linkwarden due to the amount of time it saves!

**Comment by mykytaui** [comment]
> @emilkowalski I'm facing the exact issue @yoannakr is facing, any updates? And btw thanks for this awesome work, I'll definitely be using this for Linkwarden due to the amount of time it saves!

same here :DD

**Comment by emilkowalski** [comment]
This has been fixed in #219, I updated the package on npm so you guys can update and get it working right away. Have a nice Sunday!

**Comment by asobirov** [comment]
Seems like this issue is still present when used with @tanstack/react-virtual. Unfortunately, I don't have a repro currently, will try to make one when i can. I'm currently not sure what specifically causing this though, but it seems to work all good without the tanstack virtual

**Comment by asobirov** [comment]
Couldn't replicate the exact behaviour, but if you try scrolling down a bit (seems like the items lower the initial 100vh) and click the drawer trigger then the drawer won't open - https://codesandbox.io/p/devbox/drawer-scrolls-to-top-forked-mx755p.

I pretty much put the code from [tanstack window example](https://tanstack.com/virtual/latest/docs/framework/react/examples/window) into the [OP's repro](https://codesandbox.io/p/sandbox/drawer-scrolls-to-top-8lpqx9).

I think the scroll to the top issue also may occur if window + infinite scroll is used (rough guess, since that's what im using)

**Comment by OrenMag** [comment]
I'm experiencing the same, on lastest version - upon opening the Drawer - the `body` styles are reset causing the page to jump to the top (not even scroll) - that's the body once the drawer opens:
<img width="312" alt="Screenshot 2024-04-04 at 20 21 20" src="https://github.com/emilkowalski/vaul/assets/78356438/578b3af0-2e29-4bb9-acfe-2fa9cb48dda7">

**Comment by OrenMag** [comment]
@franzwilhelm Opened an issue here:
https://github.com/emilkowalski/vaul/issues/318

**Comment by daniel31x13** [comment]
To all the folks who are still encountering the issue, as @yoannakr pointed out, you have 
`html { scroll-behavior: smooth; }` 
somewhere in your code. Remove that and it’ll be fixed.

**Comment by OrenMag** [comment]
That's not the case for us, no `html { scroll-behavior: smooth; }` in our code base ...

> To all the folks who are still encountering the issue, as @yoannakr pointed out, you have `html { scroll-behavior: smooth; }` somewhere in your code. Remove that and it’ll be fixed.

**Comment by khoabt94** [comment]
hi, anyone can fix the undesirably scroll to top after closing drawer

**Comment by nc1z** [comment]
still getting a sharp spike to the top when opening the drawer

**Comment by nc1z** [comment]
> hi, anyone can fix the undesirably scroll to top after closing drawer

Downgrade to 0.9.2 it worked for me. I think the bug was reintroduced in 0.9.3 / 0.9.4

**Comment by Jwlee134** [comment]
I experienced the same issue, and removing explicit height style(100dvh) in my body tag worked for me

**Comment by otabekoff** [comment]
This error is happening again and again.
