### ISSUE TITLE
useLayoutEffect() throws SSR warnings when not in Next js with server components

### ISSUE THREAD

**Issue by tbakerx** [emilkowalski/vaul#17]
The `usePreventScroll()` hook makes use of `useLayoutEffect()` when the `<Drawer.Root>` component is mounted. For anyone not using NextJs with server components or explicitly mounting on client side only, this will throw SSR warnings. An easy fix could be to switch this out for an isomorphic layout effect.

```typescript
import { useEffect, useLayoutEffect } from 'react'

export const useIsomorphicLayoutEffect =
  typeof window !== 'undefined' ? useLayoutEffect : useEffect
  ```

**Comment by emilkowalski** [comment]
Fixed in #23

**Comment by traed** [comment]
@emilkowalski Still an issue here: https://github.com/emilkowalski/vaul/blob/40d3a69825df25e04ffe1e52c99c3461d785f31a/src/index.tsx#L456
