### ISSUE TITLE
Text in drawer can't be selected

### ISSUE THREAD

**Issue by dmytro-ulianov** [emilkowalski/vaul#346]
There was already a similar issue before: https://github.com/emilkowalski/vaul/issues/295.

It looks like the **#182 (drawer handle component)** discards the changes introduced in **#314 (block swipe if in wrong direction)**.

My guess is that this change from #314 was reverted in drawer handle PR and that's the reason why text selection is not working
![image](https://github.com/emilkowalski/vaul/assets/6690705/0b4c2d81-8a71-4b98-93ec-ea06a4b09649)

**Comment by shrihari-prakash** [comment]
@dmytro-ulianov did you ever find a solution?

**Comment by fruityfishy** [comment]
Facing the same issue here, is there a work around?

**Comment by shrihari-prakash** [comment]
@fruityfishy , unfortunately, this also does not seem to work for me :(. Does this solution work for you on mobile phones?

**Comment by fruityfishy** [comment]
@shrihari-prakash, ah that's unfortunate.  I haven't checked on mobile but I can confirm it works on web.

**Comment by shrihari-prakash** [comment]
Hello @emilkowalski , would there be any plan to fix this? Or would you possibly know any workarounds that we could try to solve this issue? Would appreciate any clue on how to resolve this.

**Comment by dmytro-ulianov** [comment]
@shrihari-prakash, i plan to investigate this issue within the next week or two to determine how it can be resolved. 
and i believe the changes proposed in https://github.com/emilkowalski/vaul/pull/314 should meet our needs.

**Comment by zzh8829** [comment]
> @fruityfishy , unfortunately, this also does not seem to work for me :(. Does this solution work for you on mobile phones?

you can fix it with `!select-text` in tailwind or !important with regular css

**Comment by emilkowalski** [comment]
Fixed in #291

**Comment by dmytro-ulianov** [comment]
@emilkowalski do you think it makes sense to reopen this issue since it hasn't been really resolved?

[here's the discussion on twitter](https://x.com/emilkowalski_/status/1839395830522159531)

**Comment by aparent-emgs** [comment]
I still have this same issue on 1.1.2

**Comment by vurhd** [comment]
Still an issue. Text selection by dragging is not working. cc @emilkowalski

**Comment by pranaymohan** [comment]
> Still an issue. Text selection by dragging is not working. cc @emilkowalski

I'm still running into the same issue that @vurhd flagged -- I can select individual words, but cannot drag the selection pins on mobile in a textarea

I've tried the suggestions above, but nothing works. Has anyone figured out how to resolve it?

**Comment by aryomuzakki** [comment]
@pranaymohan have u tried suggestion from @leontin2012 ?

> The onPointerDownCapture event seems to be the culprit somehow, at least for overflowing inside an input element. The data-vaul-no-drag attribute is nice since we wont accidentally drag when selecting text. Adding the following props seem to resolve it for me:
> 
> ```
> <input data-vaul-no-drag="true" onPointerDownCapture={(e) => e.nativeEvent.stopImmediatePropagation()} />
> ```
> 
> If this fix is unrelated to the original issue, please let me know!

This can prevent the dragging issue for an element, combine with `!select-text` className from tailwind to allow text selection. or css style `user-select: text !important;`

**Comment by vurhd** [comment]
It still doesn't work. I can't seem to select any text inside the drawer properly on iOS Safari. 

Individual word selection works, but I can't hold and drag to select text afterward.

**Comment by matthova** [comment]
> The onPointerDownCapture event seems to be the culprit somehow, at least for overflowing inside an input element. The data-vaul-no-drag attribute is nice since we wont accidentally drag when selecting text. Adding the following props seem to resolve it for me:
> 
> ```
> <input data-vaul-no-drag="true" onPointerDownCapture={(e) => e.nativeEvent.stopImmediatePropagation()} />
> ```
> 
> If this fix is unrelated to the original issue, please let me know!

Thanks for sharing your solution. Confirmed working for me on web and mobile 🎉

**Comment by matthova** [comment]
Wanted to note - for me, the `data-vaul-no-drag="true"` was unnecessary

**Comment by pranaymohan** [comment]
@aryomuzakki thanks for the suggestion -- I added the `onPointerDownCapture` solution and also added `!select-text` as a tailwind class, but still running into the same issue.

Similar to @vurhd I can select individual words, but cannot drag the selection pins to select other words or characters. Are you able to drag the selection pins?

I'm using Vaul v1.1.2 and Chrome on iOS.

**Comment by pere-seapoint** [comment]
> @shrihari-prakash, following worked for me: 
<Drawer.Content className="select-text">
                This is your drawer content
</Drawer.Content>

This didn't work for me but adding `data-[vaul-drawer]:select-text` seemed to do the trick

**Comment by maiconcarraro** [comment]
the original issue may be related to this one from radix/react-remove-scroll:: https://github.com/theKashey/react-remove-scroll/issues/130#issuecomment-3289696067

**Comment by anamay-saxena-1mind** [comment]
I fixed this issue by passing handleOnly=true to drawer.root, which removes the drag functionality entirely (allowing only dragging through the handle element if any) after which text select starts working

**Comment by valeriavodianchuk** [comment]
Any news? Still not working on mobile safari. `handleOnly=true` not helping
