### ISSUE TITLE
0.9.4 Does not fully respect noBodyStyles & modal={false}

### ISSUE THREAD

**Issue by uhlenbrock** [emilkowalski/vaul#432]
As soon as the drawer is opened in 0.9.4, the style `pointer-events: none` is added to the `<body>` regardless of setting `noBodyStyles` and/or `modal={false}`.

**Comment by emilkowalski** [comment]
I'm unable to reproduce. Please provide a demo with reproduction.

**Comment by viktorrenkema** [comment]
I'm experiencing the same issue, here's a forked example file that shows the issue: https://codesandbox.io/p/devbox/drawer-snap-points-forked-3v7jlr?workspaceId=c111e220-c0ec-479d-81c2-c45f851464bd

- `noBodyStyles` and `modal={false}` are both applied on the root
- despite that, the `body` has `pointer-events: none`

**Comment by viktorrenkema** [comment]
Perhaps related to radix' https://github.com/radix-ui/primitives/issues/2122, seemingly fixed by bumping @radix-ui/react-dialog to 1.1.1

**Comment by emilkowalski** [comment]
I might be missing something, but I'm able to interact with the background in the demo you provided and `body` doesn't have `pointer-events: none` for me 🤔 
https://github.com/user-attachments/assets/8723e010-2fc6-43ef-a273-84d25e92284b

**Comment by viktorrenkema** [comment]
Very odd, I also screenshotted it when it was still not working:

![image](https://github.com/user-attachments/assets/44ab7e51-1e59-4b7c-b2bd-b58f02217f56)

I'll look into it and report back if I can repro again.

**Comment by yatskovanatoly** [comment]
In @viktorrenkema demo i also found no problem regarding pointer-events on body, although i had a similar issue with Vaul, which was fixed by this hook from https://github.com/radix-ui/primitives/issues/2122 

```  useEffect(() => {
    if (open) {
      // Pushing the change to the end of the call stack
      const timer = setTimeout(() => {
        document.body.style.pointerEvents = '';
      }, 0);

      return () => clearTimeout(timer);
    } else {
      document.body.style.pointerEvents = 'auto';
    }
  }, [open]);```

my case uses custom Fab in document.body, but when the Drawer opens (no matter where it portals to - body or a custom container) the Fab receive no pointer-events

**Comment by Eldrac** [comment]
Unfortunately still seeing this behavior on 0.9.6 with
```
    <Drawer
      open={true}
      modal={false}
      dismissible={false}
      noBodyStyles={true}
```

**Comment by m-nathani** [comment]
Facing the same issue 

> Unfortunately still seeing this behavior on 0.9.6 with
> 
> ```
>     <Drawer
>       open={true}
>       modal={false}
>       dismissible={false}
>       noBodyStyles={true}
> ```
> 
> Example: https://codesandbox.io/p/devbox/drawer-snap-points-forked-lsjwfc?workspaceId=0a14cb78-5417-4f67-a82a-ad9f290ad361

I can approve this is still happening 

```
    <Drawer
      open={isConsentDrawerOpen}
      onClose={() => setIsConsentDrawerOpen(false)}
      direction="bottom"
      dismissible={false}
      modal={false}
      noBodyStyles
    >
```

**Comment by kylethacker** [comment]
Same. Updating recently, with the radix update, is causing pointer-events: none; on the body, even with modal false, dismissible false, and no body styles.

**Comment by SamStenner** [comment]
Same issue here

**Comment by emilkowalski** [comment]
Thanks for a clear repro demo @Eldrac. This should be fixed in #449. I tested it locally and everything worked fine.

Not closing this issue until I release a new version later today and you guys confirm that it's working as expedcted.

**Comment by emilkowalski** [comment]
I've just released a new version, could you verify whether it works?

**Comment by kylethacker** [comment]
> I've just released a new version, could you verify whether it works?

Fixed for me!

**Comment by Eldrac** [comment]
Me as well, thanks for your work on the library!

**Comment by clintonlunn** [comment]
Been following this also. It works now, thanks for your time and work!

**Comment by SamStenner** [comment]
Worked for me - thanks, much appreciated! :)

**Comment by reynaldichernando** [comment]
For future readers, you need to have the `<Drawer.Overlay />` element for the fix to work.

I was confused as to why the `modal={false}` still doesn't work on version 1.0.0, turns out because I didn't use the `<Drawer.Overlay />` element, adding it fixes the issue.

**Comment by KajSzy** [comment]
> For future readers, you need to have the `<Drawer.Overlay />` element for the fix to work.
> 
> I was confused as to why the `modal={false}` still doesn't work on version 1.0.0, turns out because I didn't use the `<Drawer.Overlay />` element, adding it fixes the issue.

There is a chance it won't be needed ;)
https://github.com/emilkowalski/vaul/pull/460

**Comment by viktorrenkema** [comment]
> For future readers, you need to have the `<Drawer.Overlay />` element for the fix to work.
> 
> I was confused as to why the `modal={false}` still doesn't work on version 1.0.0, turns out because I didn't use the `<Drawer.Overlay />` element, adding it fixes the issue.

Lifesaver, thanks man.

**Comment by danieldunderfelt** [comment]
This just started happening for me. I am using the Shadcn Drawer, and trying to make a drawer that is always open. This worked yesterday, but now body gets pointer-events: none for some reason.

Props:

```<Drawer
      modal={false}
      snapPoints={snapPoints}
      activeSnapPoint={activeSnapPoint}
      open={true}
      noBodyStyles={true}
      dismissible={false}
      setActiveSnapPoint={(val) => setActiveSnapPoint(!val ? snapPoints[0] : val)}
      defaultOpen={true}>```
      
Deps:

```
"@radix-ui/react-dialog": "1.1.2",
"@radix-ui/react-popover": "1.1.2",
"vaul": "^1.1.0",
```
