### ISSUE TITLE
Problems repositioning input/textarea when keyboard appears on mobile devices (Android and iPhone)

### ISSUE THREAD

**Issue by KevSalom** [emilkowalski/vaul#434]
https://github.com/user-attachments/assets/fd1b5a5a-59b3-4dac-976a-190bd76dfaa3

There were no issues with this last week, so I'm assuming it's due to the two recent updates. 

I tried setting "repositionInputs" to True or False and the problem continues.

I tried with several devices and in some cases it is much worse, the white fragment below completely covers the input sometimes.

**Comment by k2project** [comment]
I'm having the same issue ("^0.9.4").

**Comment by emilkowalski** [comment]
Should be fixed in #441, I'll release a new version later today.

**Comment by shaunkickbusch** [comment]
Still getting this on 1.0.0. Tried with the repositionInputs to true and false and still getting the same behaviour. I'm using snappoints.

**Comment by emilkowalski** [comment]
Can you provide a demo with reproduction? @shaunkickbusch

**Comment by varghesethomase** [comment]
https://github.com/user-attachments/assets/339f9269-aef3-478a-8c4e-d7c09d1ad705

@emilkowalski I face the same issue.

```
'use client';

import { memo, useState } from 'react';

import clsx from 'clsx';
import { Drawer } from 'vaul';

import { useMediaQuery } from '@/hooks/useMediaQuery';

import styles from './VaulDrawer.module.css';

const snapPoints = [0.35, 0.85];

const VaulDrawer = memo(function VaulDrawer({
  children,
}: {
  children: React.ReactNode;
}) {
  const [snap, setSnap] = useState<number | string | null>(snapPoints[0]);
  // TODO: cannot use postcss-custom-media in js files, rethink abstracting value to a variable
  const isMobile = useMediaQuery('(max-width: 768px)');

  const canScroll = snap === snapPoints.at(-1);

  return (
    <Drawer.Root
      defaultOpen={false}
      open={isMobile}
      modal={false}
      direction='bottom'
      dismissible={false}
      handleOnly={false}
      snapPoints={snapPoints}
      activeSnapPoint={snap}
      setActiveSnapPoint={setSnap}
      repositionInputs={true}
    >
      {/* <Drawer.Overlay style={{ inset: 0, display: 'fixed' }} /> */}
      <Drawer.Portal>
        <Drawer.Content className={styles.content}>
          <Drawer.Handle />
          <Drawer.Title hidden>
            Bottom sheet with information
          </Drawer.Title>
          <div
            className={clsx(styles.contentWrapper, {
              [styles.scrollable]: canScroll,
            })}
          >
            {children}
          </div>
        </Drawer.Content>
      </Drawer.Portal>
    </Drawer.Root>
  );
});

export default VaulDrawer;

```

**Comment by varghesethomase** [comment]
@emilkowalski could we reopen this ticket or give me guidance on how to solve this?
